### ISSUE TITLE
question

### ISSUE THREAD

**Issue by upexcel** [upexcel/meteor_angular2_bank#14]
meteor_angular2_bank/client/imports/adduserComponent/adduser.component.ts

  Tracker.autorun(function () {
    Meteor.subscribe("userData");

   });

why is tracker.autorun required here?

**Comment by upexcel** [comment]
u have imported moment library in this file but where is it used?

**Comment by excellencetechnologies** [comment]
sir i have changed code. removed moment library.
removed Tracker autorun.
